[package]
name = "tiles3d"
version = "0.1.0"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
edition = "2018"

[dependencies]
byteorder = "1.4.3"
serde = "1.0.125"
serde_derive = "1.0.125"
serde_json = "1.0.64"
